_wandb:
    value:
        cli_version: 0.25.1
        e:
            wxm3xkdphl2pgakama2ef8h7a39gmwax:
                args:
                    - --save-ckpt
                    - outputs/tinystories/ckpt.pt
                email: sbae12@u.rochester.edu
                executable: /Users/sbae703/Research/ML/cs336/assignment1-basics/.venv/bin/python
                git:
                    commit: 76be52a2f5f6fdf3e9e582210d025a173fdbcc6f
                host: MacBook-Pro-71.local
                os: macOS-26.6.2-arm64-arm-64bit-Mach-O
                program: -m cs336_basics.train
                python: CPython 3.14.7
                root: /Users/sbae703/Research/ML/cs336/assignment1-basics
                startedAt: "2026-10-05T21:02:37.520659Z"
                writerId: wxm3xkdphl2pgakama2ef8h7a39gmwax
        m: []
        python_version: 3.14.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 19
            "4": 3.14.7
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-arm64
learning_rate:
    value: 0.001
