_wandb:
    value:
        cli_version: 0.25.1
        e:
            g3fcv92ympqkhoh4jcu7f2iyv0c37h6u:
                apple: {}
                args:
                    - --save-ckpt=./outputs/tinystories/ckpt.pt
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "478600306688"
                email: sbae12@u.rochester.edu
                executable: /Users/sbae703/Research/ML/cs336/assignment1-basics/.venv/bin/python3
                git:
                    commit: 76be52a2f5f6fdf3e9e582210d025a173fdbcc6f
                host: MacBook-Pro-71.local
                memory:
                    total: "25769803776"
                os: macOS-26.6.2-arm64-arm-64bit-Mach-O
                program: -m cs336_basics.train
                python: CPython 3.14.7
                root: /Users/sbae703/Research/ML/cs336/assignment1-basics
                startedAt: "2026-10-05T21:55:15.622570Z"
                writerId: g3fcv92ympqkhoh4jcu7f2iyv0c37h6u
        m: []
        python_version: 3.14.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 19
            "4": 3.14.7
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-arm64
learning_rate:
    value: 0.001
